"use strict";
const DEFAULT_RACES=["人类","兽人","精灵","机器人","中性","其他"],DEFAULT_FPS=["30","60"],state={items:[],sources:[],races:[],tags:[],fps:[],source:null,race:null,tag:null,search:""};let IS_LOCAL=false,editingId=null;
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(){try{IS_LOCAL=(await fetch("./api/status")).ok}catch(e){IS_LOCAL=false}try{const d=await fetch(IS_LOCAL?"./api/items":"./data.json",{cache:"no-store"}).then(r=>r.json());state.items=d.items||[];state.sources=d.enums?.sources||[];state.races=d.enums?.races||DEFAULT_RACES;state.tags=d.enums?.tags||[];state.fps=d.enums?.fps||DEFAULT_FPS}catch(e){state.items=[];state.fps=DEFAULT_FPS}$("#upload").classList.toggle("hidden",!IS_LOCAL);$("#settings").classList.toggle("hidden",!IS_LOCAL);renderFilters();render()}
function chips(id,values,active,attr){$(id).innerHTML=values.map(v=>`<button class="chip ${active===v?"active":""}" data-${attr}="${esc(v)}">${esc(v)}</button>`).join("")}
function renderFilters(){chips("#sourceFilters",state.sources,state.source,"s");chips("#raceFilters",state.races,state.race,"r");chips("#tagFilters",state.tags,state.tag,"t")}
function render(){const list=state.items.filter(i=>(!state.source||i.source===state.source)&&(!state.race||(i.race||i.gender)===state.race)&&(!state.tag||(i.tags||[]).includes(state.tag))&&(!state.search||String(i.name).toLowerCase().includes(state.search)));$("#empty").classList.toggle("hidden",state.items.length>0);$("#grid").innerHTML=list.map(card).join("")}
function card(i){const edit=IS_LOCAL?`<button class="card-action" data-edit="${esc(i.id)}" title="编辑">✎</button><button class="card-action danger" data-delete="${esc(i.id)}" title="删除">🗑</button>`:"";return `<article class="card"><div class="preview"><img src="${esc(i.preview_url||"")}" alt="${esc(i.name)} 预览" loading="lazy"></div><div class="card-content"><div><div class="card-name" title="${esc(i.name)}">${esc(i.name)}</div><div class="tags"><span class="tag gender">${esc(i.race||i.gender||"")}</span>${i.source?`<span class="tag source">${esc(i.source)}</span>`:""}${(i.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div><div class="fps-row">${esc(i.fps||"30")} FPS</div></div><div class="card-actions">${edit}<a class="card-action" href="${esc(i.glb_url)}" download title="下载 GLB">↓</a></div></div></article>`}
$("#search").oninput=e=>{state.search=e.target.value.trim().toLowerCase();render()};[["#sourceFilters","source","s"],["#raceFilters","race","r"],["#tagFilters","tag","t"]].forEach(([id,key,a])=>$(id).onclick=e=>{const b=e.target.closest(`[data-${a}]`);if(b){state[key]=state[key]===b.dataset[a]?null:b.dataset[a];renderFilters();render()}});
function formChips(id,values,selected,multi){$(id).innerHTML=values.map(v=>`<button type="button" class="chip ${selected.includes(v)?"active":""}" data-form-value="${esc(v)}">${esc(v)}</button>`).join("")}
function openForm(item=null){editingId=item?.id||null;$("#formTitle").textContent=item?"编辑动画":"上传动画";$("#submitUpload").textContent=item?"保存修改":"上传并保存";$("#name").value=item?.name||"";formChips("#sourceChoices",state.sources,item?.source?[item.source]:[],false);formChips("#raceChoices",state.races,item?.race||item?.gender?[item.race||item.gender]:[],false);formChips("#tagChoices",state.tags,item?.tags||[],true);formChips("#fpsChoices",state.fps,item?.fps?[String(item.fps)]:[state.fps[0]||"30"],false);$("#tags").value="";$("#preview").required=!item;$("#glb").required=!item;$("#preview").value="";$("#glb").value="";$("#uploadStatus").textContent="";$("#uploadDialog").showModal()}
$("#upload").onclick=()=>openForm();document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());$("#grid").onclick=async e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(edit){openForm(state.items.find(i=>i.id===edit.dataset.edit));return}if(del){const item=state.items.find(i=>i.id===del.dataset.delete);if(!item||!confirm(`确定删除“${item.name}”及其所有文件吗？`))return;const r=await fetch(`./api/items/${item.id}`,{method:"DELETE"}),d=await r.json();if(!r.ok){alert(d.error||"删除失败");return}load()}};$("#addSource").onclick=()=>addEnum("sources","来源");$("#addRace").onclick=()=>addEnum("races","种族");$("#addTag").onclick=()=>addEnum("tags","标签");$("#addFps").onclick=()=>addEnum("fps","FPS");["#sourceChoices","#raceChoices","#tagChoices","#fpsChoices"].forEach(id=>$(id).onclick=e=>{const b=e.target.closest("[data-form-value]");if(!b)return;const box=$(id),multi=id==="#tagChoices";if(multi)b.classList.toggle("active");else{box.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active")}});
async function addEnum(kind,label){const value=prompt(`输入新的${label}`)?.trim();if(!value)return;try{const r=await fetch("./api/enums",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,value})}),d=await r.json();if(!r.ok)throw Error(d.error||"新增失败");const oldSource=$("#sourceChoices .active")?.dataset.formValue||"",oldRace=$("#raceChoices .active")?.dataset.formValue||"",oldTags=[...document.querySelectorAll("#tagChoices .active")].map(x=>x.dataset.formValue),oldFps=$("#fpsChoices .active")?.dataset.formValue||"30";state.sources=d.enums.sources||[];state.races=d.enums.races||[];state.tags=d.enums.tags||[];state.fps=d.enums.fps||DEFAULT_FPS;renderFilters();formChips("#sourceChoices",state.sources,oldSource?[oldSource]:[],false);formChips("#raceChoices",state.races,oldRace?[oldRace]:[],false);formChips("#tagChoices",state.tags,oldTags,false);formChips("#fpsChoices",state.fps,[oldFps],false);const box=kind==="sources"?"#sourceChoices":kind==="races"?"#raceChoices":kind==="tags"?"#tagChoices":"#fpsChoices";$(box).querySelector(`[data-form-value="${CSS.escape(value)}"]`)?.click()}catch(e){alert(e.message)}}
async function saveItem(){const status=$("#uploadStatus"),btn=$("#submitUpload"),fd=new FormData();const source=$("#sourceChoices .active")?.dataset.formValue||"",race=$("#raceChoices .active")?.dataset.formValue||"",fps=$("#fpsChoices .active")?.dataset.formValue||"30",tags=[...document.querySelectorAll("#tagChoices .active")].map(x=>x.dataset.formValue);fd.set("name",$("#name").value.trim());fd.set("source",source);fd.set("race",race);fd.set("fps",fps);fd.set("tags",tags.join(","));if($("#preview").files[0])fd.set("preview",$("#preview").files[0]);if($("#glb").files[0])fd.set("glb",$("#glb").files[0]);btn.disabled=true;status.textContent="正在保存…";try{const url=editingId?`./api/items/${editingId}`:"./api/upload",r=await fetch(url,{method:editingId?"PUT":"POST",body:fd}),d=await r.json();if(!r.ok)throw Error(d.error||"保存失败");status.textContent="保存完成";setTimeout(()=>{$("#uploadDialog").close();load()},500)}catch(e){status.textContent=`保存失败：${e.message}`}finally{btn.disabled=false}}
$("#uploadForm").onsubmit=e=>{e.preventDefault();saveItem()};$("#submitUpload").onclick=e=>{e.preventDefault();saveItem()};
const ENUM_LABELS={sources:"来源",races:"种族",tags:"其他标签"};function renderSettings(){const box=$("#enumGroups");box.innerHTML=Object.entries(ENUM_LABELS).map(([kind,label])=>`<section class="enum-group"><div class="enum-head"><span>${label}</span><button type="button" class="mini-button" data-enum-add="${kind}">＋新增</button></div><div class="enum-items">${(state[kind]||[]).map(v=>`<div class="enum-item"><span>${esc(v)}</span><button type="button" data-enum-ren="${esc(kind)}" data-value="${esc(v)}">改名</button><button type="button" data-enum-del="${esc(kind)}" data-value="${esc(v)}">删除</button></div>`).join("")}</div></section>`).join("")}
$("#settings").onclick=()=>{renderSettings();$("#settingsDialog").showModal()};$("#enumGroups").onclick=async e=>{const add=e.target.closest("[data-enum-add]"),ren=e.target.closest("[data-enum-ren]"),del=e.target.closest("[data-enum-del]");try{if(add){const v=prompt(`输入新的${ENUM_LABELS[add.dataset.enumAdd]}`)?.trim();if(v)await enumRequest("POST",add.dataset.enumAdd,v)}else if(ren){const v=prompt("输入新名称",ren.dataset.value)?.trim();if(v)await enumRequest("PUT",ren.dataset.enumRen,v,ren.dataset.value)}else if(del){if(confirm(`确定删除“${del.dataset.value}”吗？`))await enumRequest("DELETE",del.dataset.enumDel,del.dataset.value)}}catch(x){alert(x.message)}};async function enumRequest(method,kind,value,old=""){const r=await fetch("./api/enums",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,value,old})}),d=await r.json();if(!r.ok)throw Error(d.error||"枚举操作失败");state.sources=d.enums.sources||[];state.races=d.enums.races||[];state.tags=d.enums.tags||[];renderSettings();renderFilters();render()}
document.documentElement.dataset.theme="dark";
const login=$("#loginScreen");function unlock(){login.remove();load()}if(sessionStorage.getItem("glb-auth")==="ok")unlock();$("#loginForm").onsubmit=e=>{e.preventDefault();if($("#password").value==="110110"){sessionStorage.setItem("glb-auth","ok");unlock()}else{$("#loginError").textContent="密码不正确";$("#password").select()}};
window.addEventListener("unhandledrejection",e=>{const message=e.reason?.message||String(e.reason||"未知错误");if(message.includes("删除")||message.includes("API"))alert(`操作失败：${message}`)});
const _openForm=openForm;openForm=function(item=null){_openForm(item);$("#submitUpload").textContent=item?"修改":"上传并保存"};
$("#glb").onchange=()=>{const file=$("#glb").files[0];if(file&&!editingId)$("#name").value=file.name.replace(/\.glb$/i,"")};
