"use strict";
const DEFAULT_RACES=["人类","兽人","精灵","机器人","中性","其他"],state={items:[],sources:[],races:[],tags:[],source:null,race:null,tag:null,search:""};let IS_LOCAL=false,editingId=null;
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(){try{IS_LOCAL=(await fetch("./api/status")).ok}catch(e){IS_LOCAL=false}try{const d=await fetch(IS_LOCAL?"./api/items":"./data.json",{cache:"no-store"}).then(r=>r.json());state.items=d.items||[];state.sources=d.enums?.sources||[];state.races=d.enums?.races||DEFAULT_RACES;state.tags=d.enums?.tags||[]}catch(e){state.items=[]}$("#upload").classList.toggle("hidden",!IS_LOCAL);$("#settings").classList.toggle("hidden",!IS_LOCAL);renderFilters();render()}
function chips(id,values,active,attr){$(id).innerHTML=values.map(v=>`<button class="chip ${active===v?"active":""}" data-${attr}="${esc(v)}">${attr==="t"?"#":""}${esc(v)}</button>`).join("")}
function renderFilters(){chips("#sourceFilters",state.sources,state.source,"s");chips("#raceFilters",state.races,state.race,"r");chips("#tagFilters",state.tags,state.tag,"t")}
function render(){const list=state.items.filter(i=>(!state.source||i.source===state.source)&&(!state.race||(i.race||i.gender)===state.race)&&(!state.tag||(i.tags||[]).includes(state.tag))&&(!state.search||String(i.name).toLowerCase().includes(state.search)));$("#empty").classList.toggle("hidden",state.items.length>0);$("#grid").innerHTML=list.map(card).join("")}
function card(i){const edit=IS_LOCAL?`<button class="card-action" data-edit="${esc(i.id)}" title="编辑">✎</button>`:"";return `<article class="card"><div class="preview"><img src="${esc(i.preview_url||"")}" alt="${esc(i.name)} 预览" loading="lazy"></div><div class="card-content"><div><div class="card-name" title="${esc(i.name)}">${esc(i.name)}</div><div class="tags"><span class="tag gender">${esc(i.race||i.gender||"")}</span>${i.source?`<span class="tag source">${esc(i.source)}</span>`:""}${(i.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div></div><div class="card-actions">${edit}<a class="card-action" href="${esc(i.glb_url)}" download title="下载 GLB">↓</a></div></div></article>`}
$("#search").oninput=e=>{state.search=e.target.value.trim().toLowerCase();render()};[["#sourceFilters","source","s"],["#raceFilters","race","r"],["#tagFilters","tag","t"]].forEach(([id,key,a])=>$(id).onclick=e=>{const b=e.target.closest(`[data-${a}]`);if(b){state[key]=state[key]===b.dataset[a]?null:b.dataset[a];renderFilters();render()}});
function fillSelect(el,values,selected,empty){el.innerHTML=(empty?`<option value="">${empty}</option>`:"")+values.map(v=>`<option value="${esc(v)}" ${v===selected?"selected":""}>${esc(v)}</option>`).join("")}
function openForm(item=null){editingId=item?.id||null;$("#formTitle").textContent=item?"编辑动画":"上传动画";$("#submitUpload").textContent=item?"保存修改":"上传并保存";$("#name").value=item?.name||"";fillSelect($("#race"),state.races,item?.race||item?.gender||"","— 选择种族 —");$("#tags").value=(item?.tags||[]).join(",");fillSelect($("#source"),state.sources,item?.source||"","— 未设置 —");fillSelect($("#tagPicker"),state.tags,"","选择已有标签");$("#preview").required=!item;$("#glb").required=!item;$("#preview").value="";$("#glb").value="";$("#uploadStatus").textContent="";$("#uploadDialog").showModal()}
$("#upload").onclick=()=>openForm();document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());$("#grid").onclick=e=>{const b=e.target.closest("[data-edit]");if(b)openForm(state.items.find(i=>i.id===b.dataset.edit))};$("#addSource").onclick=()=>addEnum("sources","来源");$("#addRace").onclick=()=>addEnum("races","种族");$("#addTag").onclick=()=>addEnum("tags","标签");$("#tagPicker").onchange=e=>{if(e.target.value){const old=$("#tags").value.trim();$("#tags").value=old?(old+","+e.target.value):e.target.value;e.target.value=""}};
async function addEnum(kind,label){const value=prompt(`输入新的${label}`)?.trim();if(!value)return;try{const r=await fetch("./api/enums",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,value})}),d=await r.json();if(!r.ok)throw Error(d.error||"新增失败");state.sources=d.enums.sources||[];state.races=d.enums.races||[];state.tags=d.enums.tags||[];if(kind==="sources")fillSelect($("#source"),state.sources,value,"— 未设置 —");if(kind==="races")fillSelect($("#race"),state.races,value,"— 选择种族 —");fillSelect($("#tagPicker"),state.tags,"","选择已有标签");renderFilters()}catch(e){alert(e.message)}}
$("#uploadForm").onsubmit=async e=>{e.preventDefault();const status=$("#uploadStatus"),btn=$("#submitUpload"),fd=new FormData();fd.set("name",$("#name").value.trim());fd.set("source",$("#source").value);fd.set("race",$("#race").value);fd.set("tags",$("#tags").value);if($("#preview").files[0])fd.set("preview",$("#preview").files[0]);if($("#glb").files[0])fd.set("glb",$("#glb").files[0]);btn.disabled=true;status.textContent="正在保存…";try{const url=editingId?`./api/items/${editingId}`:"./api/upload",r=await fetch(url,{method:editingId?"PUT":"POST",body:fd}),d=await r.json();if(!r.ok)throw Error(d.error||"保存失败");status.textContent="保存完成";setTimeout(()=>{$("#uploadDialog").close();load()},500)}catch(e){status.textContent=`保存失败：${e.message}`}finally{btn.disabled=false}};
const ENUM_LABELS={sources:"来源",races:"种族",tags:"其他标签"};function renderSettings(){const box=$("#enumGroups");box.innerHTML=Object.entries(ENUM_LABELS).map(([kind,label])=>`<section class="enum-group"><div class="enum-head"><span>${label}</span><button type="button" class="mini-button" data-enum-add="${kind}">＋新增</button></div><div class="enum-items">${(state[kind]||[]).map(v=>`<div class="enum-item"><span>${esc(v)}</span><button type="button" data-enum-ren="${esc(kind)}" data-value="${esc(v)}">改名</button><button type="button" data-enum-del="${esc(kind)}" data-value="${esc(v)}">删除</button></div>`).join("")}</div></section>`).join("")}
$("#settings").onclick=()=>{renderSettings();$("#settingsDialog").showModal()};$("#enumGroups").onclick=async e=>{const add=e.target.closest("[data-enum-add]"),ren=e.target.closest("[data-enum-ren]"),del=e.target.closest("[data-enum-del]");try{if(add){const v=prompt(`输入新的${ENUM_LABELS[add.dataset.enumAdd]}`)?.trim();if(v)await enumRequest("POST",add.dataset.enumAdd,v)}else if(ren){const v=prompt("输入新名称",ren.dataset.value)?.trim();if(v)await enumRequest("PUT",ren.dataset.enumRen,v,ren.dataset.value)}else if(del){if(confirm(`确定删除“${del.dataset.value}”吗？`))await enumRequest("DELETE",del.dataset.enumDel,del.dataset.value)}}catch(x){alert(x.message)}};async function enumRequest(method,kind,value,old=""){const r=await fetch("./api/enums",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,value,old})}),d=await r.json();if(!r.ok)throw Error(d.error||"枚举操作失败");state.sources=d.enums.sources||[];state.races=d.enums.races||[];state.tags=d.enums.tags||[];renderSettings();renderFilters();render()}
document.documentElement.dataset.theme="dark";
const login=$("#loginScreen");function unlock(){login.remove();load()}if(sessionStorage.getItem("glb-auth")==="ok")unlock();$("#loginForm").onsubmit=e=>{e.preventDefault();if($("#password").value==="110110"){sessionStorage.setItem("glb-auth","ok");unlock()}else{$("#loginError").textContent="密码不正确";$("#password").select()}};
